### ISSUE TITLE
Funktion rand()

### ISSUE THREAD

**Issue by sehrmann92** [TP1-HHU/hw3#12]
Kann es sein, dass die Funktion rand() eine schlechte Routine hat? Ich bekomme immer genau dieselben "Zufallszahlen".

Schönen Abend noch :bowtie:

**Comment by goetzlehmann** [comment]
Das ist ein Feature, kein Fehler :sunglasses: Ich habe etwas dazu unter die Aufgabe geschrieben, im wesentlichen: `srand(time(NULL))` irgendwo aufrufen bevor die "Zufallszahlen" gezogen werden, dann gibt es jedes mal neue.

**Comment by sehrmann92** [comment]
Dann muss aber noch das package ctime über #include <ctime> eingebunden werden, damit es läuft? Sonst klappt es bei mir nicht.

**Comment by goetzlehmann** [comment]
Ich hatte es befürchtet... das ist so ne Stelle wo die Compiler auf verschiedenen Betriebssystemen verschiedene Sachen treiben. Darum war es auch nicht Teil der original Aufgabe. 
Also mit `#include <ctime>` scheint man dann auf der sicheren Seite zu fahren.

**Comment by friedrichschluck** [comment]
Haben jetzt ja in VL drüber geredet ;) closed
