### ISSUE TITLE
cloning not possible

### ISSUE THREAD

**Issue by Esuena** [TP1-HHU/hw3#4]
Beim Terminal taucht ständig die Meldung auf:

"fatal: unable to access https://github.com/Esuena/hw3.git : could not resolve host github.com"

**Comment by freckhard** [comment]
Bei mir funktionierts, versuchs noch einmal?

**Comment by Esuena** [comment]
Der will einfach nicht:(
Aber ich ich mach auch nichts anderes als was ich bisher immer gemacht habe:
Fork, dann copy to bla bla und dann git clone command

**Comment by freckhard** [comment]
Aber git hast du schon drauf ja? :wink: 
Achte mal auf Tippfehler und Groß- und Kleinschreibung so wie die endung .git
Wenn das nicht klappt starte einfach mal neu und überprüfe die Internetverbindung?

*git clone https://github.com/Esuena/hw3.git* funktioniert bei mir nämlich :smile:

**Comment by Esuena** [comment]
also bei mir hoffnungsloser Fall...

**Comment by goetzlehmann** [comment]
Vielleicht hatte die Virtual Box mal wieder Internet verloren, das hatten wir ja schon mal. Das Problem ist ja eindeutig die Internetverbindung. Mein Vorschlag: Erst mal schauen ob das Internet in Windows geht. Wenn das tut, dann in der Virtual Box das Netzwerk kurz trennen (unten rechts neben der Uhr müsste ein Symbol dafür sein) und direkt wieder verbinden. Wenn Du in der Konsole dann zum Beispiel `ping www.github.com` eingibst, dann müsstest Du sehen wie der andere Rechner antwortet. Wenn das klappt, dann muss auch das clonen klappen.

**Comment by Esuena** [comment]
Hat funktioniert!!!!!!!!!!!!!!!!!!!!!!!!! DAAANKEEEEEE

**Comment by friedrichschluck** [comment]
omg wie stellt man den spam hier wieder ab :p?

**Comment by goetzlehmann** [comment]
gar nicht... wir machen hier weiter und weiter und weiter... :v:

**Comment by friedrichschluck** [comment]
trolololo! :dancer:

**Comment by Esuena** [comment]
HAHAHA

**Comment by goetzlehmann** [comment]
<a href="http://www.youtube.com/watch?feature=player_embedded&v=G8IwGUR8S54" target="_blank"><img src="http://img.youtube.com/vi/G8IwGUR8S54/0.jpg" alt="IMAGE ALT TEXT HERE" width="120" height="90" border="10" /></a>  <- link :space_invader: :speaker: :dancers:

**Comment by friedrichschluck** [comment]
:warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning:

**Comment by Gandhi-uses-nukes** [comment]
Oh, wenn es auch etwas populärer aus der Zeit sein darf:
[![Tunnel Allstars & DJ Yanny - Crockett's Theme](http://img.youtube.com/vi/AkP7EcYfL6E/0.jpg)](http://www.youtube.com/watch?v=AkP7EcYfL6E)

**Comment by friedrichschluck** [comment]
ja, kommt alle hierhin und kommentiert mit uns :grinning:

**Comment by freckhard** [comment]
Was geht denn hier ab?! :joy:

**Comment by goetzlehmann** [comment]
Ja tut sich hier jetzt nix mehr? Party schon vorbei?

**Comment by Gandhi-uses-nukes** [comment]
![image](https://suckmypic.net/odPjgAoP.jpg)
Wieso, geht doch gerade erst los ^^

**Comment by friedrichschluck** [comment]
na ich wills aber hoffen!
